package com.fmx.xiaomeng.modules.application.repository.model;

public class ArticleCategoryDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.id
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_code
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    private String categoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_name
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.introduction
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.article_num
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    private Integer articleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.bg_picture
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    private String bgPicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.id
     *
     * @return the value of article_category.id
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.id
     *
     * @param id the value for article_category.id
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_code
     *
     * @return the value of article_category.category_code
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_code
     *
     * @param categoryCode the value for article_category.category_code
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode == null ? null : categoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_name
     *
     * @return the value of article_category.category_name
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_name
     *
     * @param categoryName the value for article_category.category_name
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.introduction
     *
     * @return the value of article_category.introduction
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.introduction
     *
     * @param introduction the value for article_category.introduction
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.article_num
     *
     * @return the value of article_category.article_num
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public Integer getArticleNum() {
        return articleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.article_num
     *
     * @param articleNum the value for article_category.article_num
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public void setArticleNum(Integer articleNum) {
        this.articleNum = articleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.bg_picture
     *
     * @return the value of article_category.bg_picture
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public String getBgPicture() {
        return bgPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.bg_picture
     *
     * @param bgPicture the value for article_category.bg_picture
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    public void setBgPicture(String bgPicture) {
        this.bgPicture = bgPicture == null ? null : bgPicture.trim();
    }
}