package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class ArticleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.img_url_list
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String imgUrlList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.modified_time
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.user_nick_name
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String userNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.anonymous_name
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String anonymousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.avatar
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.display_type
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer displayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.function_type
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer functionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.thumb_up_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer thumbUpCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.view_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.collect_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer collectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.top
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Boolean top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.good
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Boolean good;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tag
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.thumb_up_ids
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String thumbUpIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.school_id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.anonymous
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Boolean anonymous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.has_delete
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Boolean hasDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.hot
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Long hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.position_info
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private String positionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.admin
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    private Boolean admin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.img_url_list
     *
     * @return the value of article.img_url_list
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getImgUrlList() {
        return imgUrlList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.img_url_list
     *
     * @param imgUrlList the value for article.img_url_list
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setImgUrlList(String imgUrlList) {
        this.imgUrlList = imgUrlList == null ? null : imgUrlList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.modified_time
     *
     * @return the value of article.modified_time
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.modified_time
     *
     * @param modifiedTime the value for article.modified_time
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_id
     *
     * @return the value of article.user_id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_id
     *
     * @param userId the value for article.user_id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.user_nick_name
     *
     * @return the value of article.user_nick_name
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.user_nick_name
     *
     * @param userNickName the value for article.user_nick_name
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.anonymous_name
     *
     * @return the value of article.anonymous_name
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getAnonymousName() {
        return anonymousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.anonymous_name
     *
     * @param anonymousName the value for article.anonymous_name
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setAnonymousName(String anonymousName) {
        this.anonymousName = anonymousName == null ? null : anonymousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.avatar
     *
     * @return the value of article.avatar
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.avatar
     *
     * @param avatar the value for article.avatar
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category
     *
     * @return the value of article.category
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category
     *
     * @param category the value for article.category
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.display_type
     *
     * @return the value of article.display_type
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getDisplayType() {
        return displayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.display_type
     *
     * @param displayType the value for article.display_type
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setDisplayType(Integer displayType) {
        this.displayType = displayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.function_type
     *
     * @return the value of article.function_type
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.function_type
     *
     * @param functionType the value for article.function_type
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setFunctionType(Integer functionType) {
        this.functionType = functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_count
     *
     * @return the value of article.comment_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_count
     *
     * @param commentCount the value for article.comment_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.thumb_up_count
     *
     * @return the value of article.thumb_up_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getThumbUpCount() {
        return thumbUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.thumb_up_count
     *
     * @param thumbUpCount the value for article.thumb_up_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setThumbUpCount(Integer thumbUpCount) {
        this.thumbUpCount = thumbUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.view_count
     *
     * @return the value of article.view_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.view_count
     *
     * @param viewCount the value for article.view_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.collect_count
     *
     * @return the value of article.collect_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.collect_count
     *
     * @param collectCount the value for article.collect_count
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.top
     *
     * @return the value of article.top
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Boolean getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.top
     *
     * @param top the value for article.top
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setTop(Boolean top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.good
     *
     * @return the value of article.good
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Boolean getGood() {
        return good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.good
     *
     * @param good the value for article.good
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setGood(Boolean good) {
        this.good = good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tag
     *
     * @return the value of article.tag
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tag
     *
     * @param tag the value for article.tag
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.thumb_up_ids
     *
     * @return the value of article.thumb_up_ids
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getThumbUpIds() {
        return thumbUpIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.thumb_up_ids
     *
     * @param thumbUpIds the value for article.thumb_up_ids
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setThumbUpIds(String thumbUpIds) {
        this.thumbUpIds = thumbUpIds == null ? null : thumbUpIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.school_id
     *
     * @return the value of article.school_id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.school_id
     *
     * @param schoolId the value for article.school_id
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.anonymous
     *
     * @return the value of article.anonymous
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Boolean getAnonymous() {
        return anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.anonymous
     *
     * @param anonymous the value for article.anonymous
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.has_delete
     *
     * @return the value of article.has_delete
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Boolean getHasDelete() {
        return hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.has_delete
     *
     * @param hasDelete the value for article.has_delete
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setHasDelete(Boolean hasDelete) {
        this.hasDelete = hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.hot
     *
     * @return the value of article.hot
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Long getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.hot
     *
     * @param hot the value for article.hot
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setHot(Long hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.position_info
     *
     * @return the value of article.position_info
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public String getPositionInfo() {
        return positionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.position_info
     *
     * @param positionInfo the value for article.position_info
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setPositionInfo(String positionInfo) {
        this.positionInfo = positionInfo == null ? null : positionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.admin
     *
     * @return the value of article.admin
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public Boolean getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.admin
     *
     * @param admin the value for article.admin
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }
}