package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class ArticleCommentDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.article_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.school_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.avatar
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_nick_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String userNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.anonymous_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String anonymousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.to_user_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Long toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.to_user_nick_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String toUserNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.to_anonymous_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String toAnonymousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_type
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Integer commentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.img_url
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_comment_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Long parentCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_comment_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Long replyCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.thumb_up_count
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Integer thumbUpCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.anonymous
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Boolean anonymous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.has_reply
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Boolean hasReply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.admin
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Boolean admin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.has_delete
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    private Boolean hasDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.article_id
     *
     * @return the value of comment.article_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.article_id
     *
     * @param articleId the value for comment.article_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.school_id
     *
     * @return the value of comment.school_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.school_id
     *
     * @param schoolId the value for comment.school_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.avatar
     *
     * @return the value of comment.avatar
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.avatar
     *
     * @param avatar the value for comment.avatar
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_nick_name
     *
     * @return the value of comment.user_nick_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_nick_name
     *
     * @param userNickName the value for comment.user_nick_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.anonymous_name
     *
     * @return the value of comment.anonymous_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getAnonymousName() {
        return anonymousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.anonymous_name
     *
     * @param anonymousName the value for comment.anonymous_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setAnonymousName(String anonymousName) {
        this.anonymousName = anonymousName == null ? null : anonymousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.to_user_id
     *
     * @return the value of comment.to_user_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.to_user_id
     *
     * @param toUserId the value for comment.to_user_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.to_user_nick_name
     *
     * @return the value of comment.to_user_nick_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getToUserNickName() {
        return toUserNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.to_user_nick_name
     *
     * @param toUserNickName the value for comment.to_user_nick_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setToUserNickName(String toUserNickName) {
        this.toUserNickName = toUserNickName == null ? null : toUserNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.to_anonymous_name
     *
     * @return the value of comment.to_anonymous_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getToAnonymousName() {
        return toAnonymousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.to_anonymous_name
     *
     * @param toAnonymousName the value for comment.to_anonymous_name
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setToAnonymousName(String toAnonymousName) {
        this.toAnonymousName = toAnonymousName == null ? null : toAnonymousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_type
     *
     * @return the value of comment.comment_type
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_type
     *
     * @param commentType the value for comment.comment_type
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.img_url
     *
     * @return the value of comment.img_url
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.img_url
     *
     * @param imgUrl the value for comment.img_url
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_comment_id
     *
     * @return the value of comment.parent_comment_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Long getParentCommentId() {
        return parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_comment_id
     *
     * @param parentCommentId the value for comment.parent_comment_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setParentCommentId(Long parentCommentId) {
        this.parentCommentId = parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_comment_id
     *
     * @return the value of comment.reply_comment_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Long getReplyCommentId() {
        return replyCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_comment_id
     *
     * @param replyCommentId the value for comment.reply_comment_id
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setReplyCommentId(Long replyCommentId) {
        this.replyCommentId = replyCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.thumb_up_count
     *
     * @return the value of comment.thumb_up_count
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Integer getThumbUpCount() {
        return thumbUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.thumb_up_count
     *
     * @param thumbUpCount the value for comment.thumb_up_count
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setThumbUpCount(Integer thumbUpCount) {
        this.thumbUpCount = thumbUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.anonymous
     *
     * @return the value of comment.anonymous
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Boolean getAnonymous() {
        return anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.anonymous
     *
     * @param anonymous the value for comment.anonymous
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.has_reply
     *
     * @return the value of comment.has_reply
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Boolean getHasReply() {
        return hasReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.has_reply
     *
     * @param hasReply the value for comment.has_reply
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setHasReply(Boolean hasReply) {
        this.hasReply = hasReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.admin
     *
     * @return the value of comment.admin
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Boolean getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.admin
     *
     * @param admin the value for comment.admin
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.has_delete
     *
     * @return the value of comment.has_delete
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public Boolean getHasDelete() {
        return hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.has_delete
     *
     * @param hasDelete the value for comment.has_delete
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    public void setHasDelete(Boolean hasDelete) {
        this.hasDelete = hasDelete;
    }
}