package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class CollectDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.article_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.create_time
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.to_user_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    private Long toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.has_delete
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    private Boolean hasDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.article_id
     *
     * @return the value of collect.article_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.article_id
     *
     * @param articleId the value for collect.article_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.create_time
     *
     * @return the value of collect.create_time
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.create_time
     *
     * @param createTime the value for collect.create_time
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.to_user_id
     *
     * @return the value of collect.to_user_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.to_user_id
     *
     * @param toUserId the value for collect.to_user_id
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.has_delete
     *
     * @return the value of collect.has_delete
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public Boolean getHasDelete() {
        return hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.has_delete
     *
     * @param hasDelete the value for collect.has_delete
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    public void setHasDelete(Boolean hasDelete) {
        this.hasDelete = hasDelete;
    }
}