package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class DingDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ding_zhu.article_id
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ding_zhu.user_id
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ding_zhu.create_time
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ding_zhu.article_id
     *
     * @return the value of ding_zhu.article_id
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ding_zhu.article_id
     *
     * @param articleId the value for ding_zhu.article_id
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ding_zhu.user_id
     *
     * @return the value of ding_zhu.user_id
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ding_zhu.user_id
     *
     * @param userId the value for ding_zhu.user_id
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ding_zhu.create_time
     *
     * @return the value of ding_zhu.create_time
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ding_zhu.create_time
     *
     * @param createTime the value for ding_zhu.create_time
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}