package com.fmx.xiaomeng.modules.application.repository.model;

public class MediaCheckRecordDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_check_record.id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_check_record.media_type
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    private Integer mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_check_record.belong_type
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    private Integer belongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_check_record.belong_Id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    private Long belongId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_check_record.trace_id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    private String traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_check_record.user_id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_check_record.id
     *
     * @return the value of media_check_record.id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_check_record.id
     *
     * @param id the value for media_check_record.id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_check_record.media_type
     *
     * @return the value of media_check_record.media_type
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public Integer getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_check_record.media_type
     *
     * @param mediaType the value for media_check_record.media_type
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_check_record.belong_type
     *
     * @return the value of media_check_record.belong_type
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public Integer getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_check_record.belong_type
     *
     * @param belongType the value for media_check_record.belong_type
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public void setBelongType(Integer belongType) {
        this.belongType = belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_check_record.belong_Id
     *
     * @return the value of media_check_record.belong_Id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public Long getBelongId() {
        return belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_check_record.belong_Id
     *
     * @param belongId the value for media_check_record.belong_Id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public void setBelongId(Long belongId) {
        this.belongId = belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_check_record.trace_id
     *
     * @return the value of media_check_record.trace_id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_check_record.trace_id
     *
     * @param traceId the value for media_check_record.trace_id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId == null ? null : traceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_check_record.user_id
     *
     * @return the value of media_check_record.user_id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_check_record.user_id
     *
     * @param userId the value for media_check_record.user_id
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}