package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class MockArticleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.school_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.content
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.img_url_list
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private String imgUrlList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.create_time
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.user_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.user_nick_name
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private String userNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.admin_user_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Long adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.category
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_article.has_delete
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    private Boolean hasDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.id
     *
     * @return the value of mock_article.id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.id
     *
     * @param id the value for mock_article.id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.school_id
     *
     * @return the value of mock_article.school_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.school_id
     *
     * @param schoolId the value for mock_article.school_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.content
     *
     * @return the value of mock_article.content
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.content
     *
     * @param content the value for mock_article.content
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.img_url_list
     *
     * @return the value of mock_article.img_url_list
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public String getImgUrlList() {
        return imgUrlList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.img_url_list
     *
     * @param imgUrlList the value for mock_article.img_url_list
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setImgUrlList(String imgUrlList) {
        this.imgUrlList = imgUrlList == null ? null : imgUrlList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.create_time
     *
     * @return the value of mock_article.create_time
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.create_time
     *
     * @param createTime the value for mock_article.create_time
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.user_id
     *
     * @return the value of mock_article.user_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.user_id
     *
     * @param userId the value for mock_article.user_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.user_nick_name
     *
     * @return the value of mock_article.user_nick_name
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.user_nick_name
     *
     * @param userNickName the value for mock_article.user_nick_name
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.admin_user_id
     *
     * @return the value of mock_article.admin_user_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Long getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.admin_user_id
     *
     * @param adminUserId the value for mock_article.admin_user_id
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setAdminUserId(Long adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.category
     *
     * @return the value of mock_article.category
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.category
     *
     * @param category the value for mock_article.category
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_article.has_delete
     *
     * @return the value of mock_article.has_delete
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public Boolean getHasDelete() {
        return hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_article.has_delete
     *
     * @param hasDelete the value for mock_article.has_delete
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    public void setHasDelete(Boolean hasDelete) {
        this.hasDelete = hasDelete;
    }
}