package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class NotificationDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.article_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Long articleId;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.source_comment_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Long sourceCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.article_comment_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Long articleCommentId;





    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.user_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.user_nick_name
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private String userNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.avatar
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.target_user_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Long targetUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notice_type
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Integer noticeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.create_time
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.already_read
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Boolean alreadyRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.content
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.has_delete
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    private Boolean hasDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.article_id
     *
     * @return the value of notification.article_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.article_id
     *
     * @param articleId the value for notification.article_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.source_comment_id
     *
     * @return the value of notification.source_comment_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Long getSourceCommentId() {
        return sourceCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.source_comment_id
     *
     * @param sourceCommentId the value for notification.source_comment_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setSourceCommentId(Long sourceCommentId) {
        this.sourceCommentId = sourceCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.article_comment_id
     *
     * @return the value of notification.article_comment_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Long getArticleCommentId() {
        return articleCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.article_comment_id
     *
     * @param articleCommentId the value for notification.article_comment_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setArticleCommentId(Long articleCommentId) {
        this.articleCommentId = articleCommentId;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.user_id
     *
     * @return the value of notification.user_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.user_id
     *
     * @param userId the value for notification.user_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.user_nick_name
     *
     * @return the value of notification.user_nick_name
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.user_nick_name
     *
     * @param userNickName the value for notification.user_nick_name
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.avatar
     *
     * @return the value of notification.avatar
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.avatar
     *
     * @param avatar the value for notification.avatar
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.target_user_id
     *
     * @return the value of notification.target_user_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Long getTargetUserId() {
        return targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.target_user_id
     *
     * @param targetUserId the value for notification.target_user_id
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setTargetUserId(Long targetUserId) {
        this.targetUserId = targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notice_type
     *
     * @return the value of notification.notice_type
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Integer getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notice_type
     *
     * @param noticeType the value for notification.notice_type
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setNoticeType(Integer noticeType) {
        this.noticeType = noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.create_time
     *
     * @return the value of notification.create_time
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.create_time
     *
     * @param createTime the value for notification.create_time
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.already_read
     *
     * @return the value of notification.already_read
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Boolean getAlreadyRead() {
        return alreadyRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.already_read
     *
     * @param alreadyRead the value for notification.already_read
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setAlreadyRead(Boolean alreadyRead) {
        this.alreadyRead = alreadyRead;
    }

    private boolean isOwner;

    public void setIsOwner(boolean isOwner) { this.isOwner = isOwner; } public boolean getIsOwner() { return isOwner; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.content
     *
     * @return the value of notification.content
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.content
     *
     * @param content the value for notification.content
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.has_delete
     *
     * @return the value of notification.has_delete
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public Boolean getHasDelete() {
        return hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.has_delete
     *
     * @param hasDelete the value for notification.has_delete
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    public void setHasDelete(Boolean hasDelete) {
        this.hasDelete = hasDelete;
    }
}