package com.fmx.xiaomeng.modules.application.repository.model;

public class OnlineTimeStatisticDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_time_statistic.user_id
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_time_statistic.date_key
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    private String dateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_time_statistic.online_duration
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    private Integer onlineDuration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_time_statistic.user_id
     *
     * @return the value of online_time_statistic.user_id
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_time_statistic.user_id
     *
     * @param userId the value for online_time_statistic.user_id
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_time_statistic.date_key
     *
     * @return the value of online_time_statistic.date_key
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    public String getDateKey() {
        return dateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_time_statistic.date_key
     *
     * @param dateKey the value for online_time_statistic.date_key
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    public void setDateKey(String dateKey) {
        this.dateKey = dateKey == null ? null : dateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_time_statistic.online_duration
     *
     * @return the value of online_time_statistic.online_duration
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    public Integer getOnlineDuration() {
        return onlineDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_time_statistic.online_duration
     *
     * @param onlineDuration the value for online_time_statistic.online_duration
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    public void setOnlineDuration(Integer onlineDuration) {
        this.onlineDuration = onlineDuration;
    }
}