package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class ReportRecordDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.create_time
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.reason
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.user_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.reported_user_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Long reportedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.report_type
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Integer reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.report_type_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Long reportTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.handle_status
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Integer handleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.school_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_record.report_valid
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    private Boolean reportValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.id
     *
     * @return the value of report_record.id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.id
     *
     * @param id the value for report_record.id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.create_time
     *
     * @return the value of report_record.create_time
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.create_time
     *
     * @param createTime the value for report_record.create_time
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.reason
     *
     * @return the value of report_record.reason
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.reason
     *
     * @param reason the value for report_record.reason
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.user_id
     *
     * @return the value of report_record.user_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.user_id
     *
     * @param userId the value for report_record.user_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.reported_user_id
     *
     * @return the value of report_record.reported_user_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Long getReportedUserId() {
        return reportedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.reported_user_id
     *
     * @param reportedUserId the value for report_record.reported_user_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setReportedUserId(Long reportedUserId) {
        this.reportedUserId = reportedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.report_type
     *
     * @return the value of report_record.report_type
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.report_type
     *
     * @param reportType the value for report_record.report_type
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.report_type_id
     *
     * @return the value of report_record.report_type_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Long getReportTypeId() {
        return reportTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.report_type_id
     *
     * @param reportTypeId the value for report_record.report_type_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setReportTypeId(Long reportTypeId) {
        this.reportTypeId = reportTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.handle_status
     *
     * @return the value of report_record.handle_status
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Integer getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.handle_status
     *
     * @param handleStatus the value for report_record.handle_status
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setHandleStatus(Integer handleStatus) {
        this.handleStatus = handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.school_id
     *
     * @return the value of report_record.school_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.school_id
     *
     * @param schoolId the value for report_record.school_id
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_record.report_valid
     *
     * @return the value of report_record.report_valid
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public Boolean getReportValid() {
        return reportValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_record.report_valid
     *
     * @param reportValid the value for report_record.report_valid
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    public void setReportValid(Boolean reportValid) {
        this.reportValid = reportValid;
    }
}