package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class ThumbUpDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.article_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.comment_Id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.user_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.to_user_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Long toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.create_time
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.thumb_up_type
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Integer thumbUpType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.has_delete
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    private Boolean hasDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.id
     *
     * @return the value of thumb_up.id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.id
     *
     * @param id the value for thumb_up.id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.article_id
     *
     * @return the value of thumb_up.article_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.article_id
     *
     * @param articleId the value for thumb_up.article_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.comment_Id
     *
     * @return the value of thumb_up.comment_Id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.comment_Id
     *
     * @param commentId the value for thumb_up.comment_Id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.user_id
     *
     * @return the value of thumb_up.user_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.user_id
     *
     * @param userId the value for thumb_up.user_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.to_user_id
     *
     * @return the value of thumb_up.to_user_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.to_user_id
     *
     * @param toUserId the value for thumb_up.to_user_id
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.create_time
     *
     * @return the value of thumb_up.create_time
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.create_time
     *
     * @param createTime the value for thumb_up.create_time
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.thumb_up_type
     *
     * @return the value of thumb_up.thumb_up_type
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Integer getThumbUpType() {
        return thumbUpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.thumb_up_type
     *
     * @param thumbUpType the value for thumb_up.thumb_up_type
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setThumbUpType(Integer thumbUpType) {
        this.thumbUpType = thumbUpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.has_delete
     *
     * @return the value of thumb_up.has_delete
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public Boolean getHasDelete() {
        return hasDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.has_delete
     *
     * @param hasDelete the value for thumb_up.has_delete
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    public void setHasDelete(Boolean hasDelete) {
        this.hasDelete = hasDelete;
    }
}