package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class UserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.anonymous_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String anonymousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.union_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.anonymous_avatar
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String anonymousAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.home_city
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String homeCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.home_province
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String homeProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.motto
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String motto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modified_time
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.score
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_password
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String studentPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.violation_times
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer violationTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.graduate_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Boolean graduateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.certification
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String certification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.continue_signed_days
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer continueSignedDays;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.auth_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer authStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.attributes
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String attributes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.enrollment_year
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer enrollmentYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stroll_school_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer strollSchoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stroll_school_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private String strollSchoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admin
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Boolean admin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Integer accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.blue_v
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    private Boolean blueV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.anonymous_name
     *
     * @return the value of user.anonymous_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getAnonymousName() {
        return anonymousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.anonymous_name
     *
     * @param anonymousName the value for user.anonymous_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAnonymousName(String anonymousName) {
        this.anonymousName = anonymousName == null ? null : anonymousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_id
     *
     * @return the value of user.open_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_id
     *
     * @param openId the value for user.open_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.union_id
     *
     * @return the value of user.union_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.union_id
     *
     * @param unionId the value for user.union_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.anonymous_avatar
     *
     * @return the value of user.anonymous_avatar
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getAnonymousAvatar() {
        return anonymousAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.anonymous_avatar
     *
     * @param anonymousAvatar the value for user.anonymous_avatar
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAnonymousAvatar(String anonymousAvatar) {
        this.anonymousAvatar = anonymousAvatar == null ? null : anonymousAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school_name
     *
     * @return the value of user.school_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school_name
     *
     * @param schoolName the value for user.school_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.home_city
     *
     * @return the value of user.home_city
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getHomeCity() {
        return homeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.home_city
     *
     * @param homeCity the value for user.home_city
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setHomeCity(String homeCity) {
        this.homeCity = homeCity == null ? null : homeCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.home_province
     *
     * @return the value of user.home_province
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getHomeProvince() {
        return homeProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.home_province
     *
     * @param homeProvince the value for user.home_province
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setHomeProvince(String homeProvince) {
        this.homeProvince = homeProvince == null ? null : homeProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.motto
     *
     * @return the value of user.motto
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.motto
     *
     * @param motto the value for user.motto
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setMotto(String motto) {
        this.motto = motto == null ? null : motto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modified_time
     *
     * @return the value of user.modified_time
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modified_time
     *
     * @param modifiedTime the value for user.modified_time
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.score
     *
     * @return the value of user.score
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.score
     *
     * @param score the value for user.score
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_id
     *
     * @return the value of user.student_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_id
     *
     * @param studentId the value for user.student_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_password
     *
     * @return the value of user.student_password
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_password
     *
     * @param studentPassword the value for user.student_password
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.violation_times
     *
     * @return the value of user.violation_times
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getViolationTimes() {
        return violationTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.violation_times
     *
     * @param violationTimes the value for user.violation_times
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setViolationTimes(Integer violationTimes) {
        this.violationTimes = violationTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school_id
     *
     * @return the value of user.school_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school_id
     *
     * @param schoolId the value for user.school_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.graduate_status
     *
     * @return the value of user.graduate_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Boolean getGraduateStatus() {
        return graduateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.graduate_status
     *
     * @param graduateStatus the value for user.graduate_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setGraduateStatus(Boolean graduateStatus) {
        this.graduateStatus = graduateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.certification
     *
     * @return the value of user.certification
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getCertification() {
        return certification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.certification
     *
     * @param certification the value for user.certification
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setCertification(String certification) {
        this.certification = certification == null ? null : certification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.continue_signed_days
     *
     * @return the value of user.continue_signed_days
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    // public Integer getContinueSignedDays() {
    //     return continueSignedDays;
    // }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.continue_signed_days
     *
     * @param continueSignedDays the value for user.continue_signed_days
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    // public void setContinueSignedDays(Integer continueSignedDays) {
    //     this.continueSignedDays = continueSignedDays;
    // }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.auth_status
     *
     * @return the value of user.auth_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.auth_status
     *
     * @param authStatus the value for user.auth_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAuthStatus(Integer authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade
     *
     * @return the value of user.grade
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.attributes
     *
     * @return the value of user.attributes
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.attributes
     *
     * @param attributes the value for user.attributes
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.enrollment_year
     *
     * @return the value of user.enrollment_year
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getEnrollmentYear() {
        return enrollmentYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.enrollment_year
     *
     * @param enrollmentYear the value for user.enrollment_year
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setEnrollmentYear(Integer enrollmentYear) {
        this.enrollmentYear = enrollmentYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stroll_school_id
     *
     * @return the value of user.stroll_school_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getStrollSchoolId() {
        return strollSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stroll_school_id
     *
     * @param strollSchoolId the value for user.stroll_school_id
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setStrollSchoolId(Integer strollSchoolId) {
        this.strollSchoolId = strollSchoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stroll_school_name
     *
     * @return the value of user.stroll_school_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getStrollSchoolName() {
        return strollSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stroll_school_name
     *
     * @param strollSchoolName the value for user.stroll_school_name
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setStrollSchoolName(String strollSchoolName) {
        this.strollSchoolName = strollSchoolName == null ? null : strollSchoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.admin
     *
     * @return the value of user.admin
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Boolean getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.admin
     *
     * @param admin the value for user.admin
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_status
     *
     * @return the value of user.account_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_status
     *
     * @param accountStatus the value for user.account_status
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.blue_v
     *
     * @return the value of user.blue_v
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Boolean getBlueV() {
        return blueV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.blue_v
     *
     * @param blueV the value for user.blue_v
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setBlueV(Boolean blueV) {
        this.blueV = blueV;
    }
}