package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.Date;

public class UserBlackDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_black.id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_black.user_id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_black.blacked_user_id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    private Long blackedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_black.create_time
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_black.modified_time
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_black.valid
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_black.id
     *
     * @return the value of user_black.id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_black.id
     *
     * @param id the value for user_black.id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_black.user_id
     *
     * @return the value of user_black.user_id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_black.user_id
     *
     * @param userId the value for user_black.user_id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_black.blacked_user_id
     *
     * @return the value of user_black.blacked_user_id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public Long getBlackedUserId() {
        return blackedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_black.blacked_user_id
     *
     * @param blackedUserId the value for user_black.blacked_user_id
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public void setBlackedUserId(Long blackedUserId) {
        this.blackedUserId = blackedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_black.create_time
     *
     * @return the value of user_black.create_time
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_black.create_time
     *
     * @param createTime the value for user_black.create_time
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_black.modified_time
     *
     * @return the value of user_black.modified_time
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_black.modified_time
     *
     * @param modifiedTime the value for user_black.modified_time
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_black.valid
     *
     * @return the value of user_black.valid
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_black.valid
     *
     * @param valid the value for user_black.valid
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}