package com.fmx.xiaomeng.modules.application.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public UserDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nick_name is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nick_name =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nick_name <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nick_name >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nick_name >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nick_name <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nick_name <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nick_name like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nick_name not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("nick_name in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("nick_name not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nick_name between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nick_name not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameIsNull() {
            addCriterion("anonymous_name is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameIsNotNull() {
            addCriterion("anonymous_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameEqualTo(String value) {
            addCriterion("anonymous_name =", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotEqualTo(String value) {
            addCriterion("anonymous_name <>", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameGreaterThan(String value) {
            addCriterion("anonymous_name >", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameGreaterThanOrEqualTo(String value) {
            addCriterion("anonymous_name >=", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameLessThan(String value) {
            addCriterion("anonymous_name <", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameLessThanOrEqualTo(String value) {
            addCriterion("anonymous_name <=", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameLike(String value) {
            addCriterion("anonymous_name like", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotLike(String value) {
            addCriterion("anonymous_name not like", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameIn(List<String> values) {
            addCriterion("anonymous_name in", values, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotIn(List<String> values) {
            addCriterion("anonymous_name not in", values, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameBetween(String value1, String value2) {
            addCriterion("anonymous_name between", value1, value2, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotBetween(String value1, String value2) {
            addCriterion("anonymous_name not between", value1, value2, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNull() {
            addCriterion("open_id is null");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNotNull() {
            addCriterion("open_id is not null");
            return (Criteria) this;
        }

        public Criteria andOpenIdEqualTo(String value) {
            addCriterion("open_id =", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotEqualTo(String value) {
            addCriterion("open_id <>", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThan(String value) {
            addCriterion("open_id >", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("open_id >=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThan(String value) {
            addCriterion("open_id <", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThanOrEqualTo(String value) {
            addCriterion("open_id <=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLike(String value) {
            addCriterion("open_id like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotLike(String value) {
            addCriterion("open_id not like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIn(List<String> values) {
            addCriterion("open_id in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotIn(List<String> values) {
            addCriterion("open_id not in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdBetween(String value1, String value2) {
            addCriterion("open_id between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotBetween(String value1, String value2) {
            addCriterion("open_id not between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andUnionIdIsNull() {
            addCriterion("union_id is null");
            return (Criteria) this;
        }

        public Criteria andUnionIdIsNotNull() {
            addCriterion("union_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnionIdEqualTo(String value) {
            addCriterion("union_id =", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotEqualTo(String value) {
            addCriterion("union_id <>", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdGreaterThan(String value) {
            addCriterion("union_id >", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdGreaterThanOrEqualTo(String value) {
            addCriterion("union_id >=", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLessThan(String value) {
            addCriterion("union_id <", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLessThanOrEqualTo(String value) {
            addCriterion("union_id <=", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLike(String value) {
            addCriterion("union_id like", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotLike(String value) {
            addCriterion("union_id not like", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdIn(List<String> values) {
            addCriterion("union_id in", values, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotIn(List<String> values) {
            addCriterion("union_id not in", values, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdBetween(String value1, String value2) {
            addCriterion("union_id between", value1, value2, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotBetween(String value1, String value2) {
            addCriterion("union_id not between", value1, value2, "unionId");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarIsNull() {
            addCriterion("anonymous_avatar is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarIsNotNull() {
            addCriterion("anonymous_avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarEqualTo(String value) {
            addCriterion("anonymous_avatar =", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarNotEqualTo(String value) {
            addCriterion("anonymous_avatar <>", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarGreaterThan(String value) {
            addCriterion("anonymous_avatar >", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("anonymous_avatar >=", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarLessThan(String value) {
            addCriterion("anonymous_avatar <", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarLessThanOrEqualTo(String value) {
            addCriterion("anonymous_avatar <=", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarLike(String value) {
            addCriterion("anonymous_avatar like", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarNotLike(String value) {
            addCriterion("anonymous_avatar not like", value, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarIn(List<String> values) {
            addCriterion("anonymous_avatar in", values, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarNotIn(List<String> values) {
            addCriterion("anonymous_avatar not in", values, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarBetween(String value1, String value2) {
            addCriterion("anonymous_avatar between", value1, value2, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andAnonymousAvatarNotBetween(String value1, String value2) {
            addCriterion("anonymous_avatar not between", value1, value2, "anonymousAvatar");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNull() {
            addCriterion("school_name is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNotNull() {
            addCriterion("school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameEqualTo(String value) {
            addCriterion("school_name =", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotEqualTo(String value) {
            addCriterion("school_name <>", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThan(String value) {
            addCriterion("school_name >", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("school_name >=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThan(String value) {
            addCriterion("school_name <", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("school_name <=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLike(String value) {
            addCriterion("school_name like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotLike(String value) {
            addCriterion("school_name not like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIn(List<String> values) {
            addCriterion("school_name in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotIn(List<String> values) {
            addCriterion("school_name not in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameBetween(String value1, String value2) {
            addCriterion("school_name between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotBetween(String value1, String value2) {
            addCriterion("school_name not between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andHomeCityIsNull() {
            addCriterion("home_city is null");
            return (Criteria) this;
        }

        public Criteria andHomeCityIsNotNull() {
            addCriterion("home_city is not null");
            return (Criteria) this;
        }

        public Criteria andHomeCityEqualTo(String value) {
            addCriterion("home_city =", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityNotEqualTo(String value) {
            addCriterion("home_city <>", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityGreaterThan(String value) {
            addCriterion("home_city >", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityGreaterThanOrEqualTo(String value) {
            addCriterion("home_city >=", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityLessThan(String value) {
            addCriterion("home_city <", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityLessThanOrEqualTo(String value) {
            addCriterion("home_city <=", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityLike(String value) {
            addCriterion("home_city like", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityNotLike(String value) {
            addCriterion("home_city not like", value, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityIn(List<String> values) {
            addCriterion("home_city in", values, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityNotIn(List<String> values) {
            addCriterion("home_city not in", values, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityBetween(String value1, String value2) {
            addCriterion("home_city between", value1, value2, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeCityNotBetween(String value1, String value2) {
            addCriterion("home_city not between", value1, value2, "homeCity");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceIsNull() {
            addCriterion("home_province is null");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceIsNotNull() {
            addCriterion("home_province is not null");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceEqualTo(String value) {
            addCriterion("home_province =", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceNotEqualTo(String value) {
            addCriterion("home_province <>", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceGreaterThan(String value) {
            addCriterion("home_province >", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("home_province >=", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceLessThan(String value) {
            addCriterion("home_province <", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceLessThanOrEqualTo(String value) {
            addCriterion("home_province <=", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceLike(String value) {
            addCriterion("home_province like", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceNotLike(String value) {
            addCriterion("home_province not like", value, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceIn(List<String> values) {
            addCriterion("home_province in", values, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceNotIn(List<String> values) {
            addCriterion("home_province not in", values, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceBetween(String value1, String value2) {
            addCriterion("home_province between", value1, value2, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andHomeProvinceNotBetween(String value1, String value2) {
            addCriterion("home_province not between", value1, value2, "homeProvince");
            return (Criteria) this;
        }

        public Criteria andMottoIsNull() {
            addCriterion("motto is null");
            return (Criteria) this;
        }

        public Criteria andMottoIsNotNull() {
            addCriterion("motto is not null");
            return (Criteria) this;
        }

        public Criteria andMottoEqualTo(String value) {
            addCriterion("motto =", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoNotEqualTo(String value) {
            addCriterion("motto <>", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoGreaterThan(String value) {
            addCriterion("motto >", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoGreaterThanOrEqualTo(String value) {
            addCriterion("motto >=", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoLessThan(String value) {
            addCriterion("motto <", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoLessThanOrEqualTo(String value) {
            addCriterion("motto <=", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoLike(String value) {
            addCriterion("motto like", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoNotLike(String value) {
            addCriterion("motto not like", value, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoIn(List<String> values) {
            addCriterion("motto in", values, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoNotIn(List<String> values) {
            addCriterion("motto not in", values, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoBetween(String value1, String value2) {
            addCriterion("motto between", value1, value2, "motto");
            return (Criteria) this;
        }

        public Criteria andMottoNotBetween(String value1, String value2) {
            addCriterion("motto not between", value1, value2, "motto");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordIsNull() {
            addCriterion("student_password is null");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordIsNotNull() {
            addCriterion("student_password is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordEqualTo(String value) {
            addCriterion("student_password =", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotEqualTo(String value) {
            addCriterion("student_password <>", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordGreaterThan(String value) {
            addCriterion("student_password >", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("student_password >=", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordLessThan(String value) {
            addCriterion("student_password <", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordLessThanOrEqualTo(String value) {
            addCriterion("student_password <=", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordLike(String value) {
            addCriterion("student_password like", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotLike(String value) {
            addCriterion("student_password not like", value, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordIn(List<String> values) {
            addCriterion("student_password in", values, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotIn(List<String> values) {
            addCriterion("student_password not in", values, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordBetween(String value1, String value2) {
            addCriterion("student_password between", value1, value2, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andStudentPasswordNotBetween(String value1, String value2) {
            addCriterion("student_password not between", value1, value2, "studentPassword");
            return (Criteria) this;
        }

        public Criteria andViolationTimesIsNull() {
            addCriterion("violation_times is null");
            return (Criteria) this;
        }

        public Criteria andViolationTimesIsNotNull() {
            addCriterion("violation_times is not null");
            return (Criteria) this;
        }

        public Criteria andViolationTimesEqualTo(Integer value) {
            addCriterion("violation_times =", value, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesNotEqualTo(Integer value) {
            addCriterion("violation_times <>", value, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesGreaterThan(Integer value) {
            addCriterion("violation_times >", value, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("violation_times >=", value, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesLessThan(Integer value) {
            addCriterion("violation_times <", value, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesLessThanOrEqualTo(Integer value) {
            addCriterion("violation_times <=", value, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesIn(List<Integer> values) {
            addCriterion("violation_times in", values, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesNotIn(List<Integer> values) {
            addCriterion("violation_times not in", values, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesBetween(Integer value1, Integer value2) {
            addCriterion("violation_times between", value1, value2, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andViolationTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("violation_times not between", value1, value2, "violationTimes");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdEqualTo(Integer value) {
            addCriterion("school_id =", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotEqualTo(Integer value) {
            addCriterion("school_id <>", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThan(Integer value) {
            addCriterion("school_id >", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("school_id >=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThan(Integer value) {
            addCriterion("school_id <", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThanOrEqualTo(Integer value) {
            addCriterion("school_id <=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIn(List<Integer> values) {
            addCriterion("school_id in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotIn(List<Integer> values) {
            addCriterion("school_id not in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdBetween(Integer value1, Integer value2) {
            addCriterion("school_id between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("school_id not between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusIsNull() {
            addCriterion("graduate_status is null");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusIsNotNull() {
            addCriterion("graduate_status is not null");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusEqualTo(Boolean value) {
            addCriterion("graduate_status =", value, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusNotEqualTo(Boolean value) {
            addCriterion("graduate_status <>", value, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusGreaterThan(Boolean value) {
            addCriterion("graduate_status >", value, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("graduate_status >=", value, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusLessThan(Boolean value) {
            addCriterion("graduate_status <", value, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("graduate_status <=", value, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusIn(List<Boolean> values) {
            addCriterion("graduate_status in", values, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusNotIn(List<Boolean> values) {
            addCriterion("graduate_status not in", values, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("graduate_status between", value1, value2, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andGraduateStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("graduate_status not between", value1, value2, "graduateStatus");
            return (Criteria) this;
        }

        public Criteria andCertificationIsNull() {
            addCriterion("certification is null");
            return (Criteria) this;
        }

        public Criteria andCertificationIsNotNull() {
            addCriterion("certification is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationEqualTo(String value) {
            addCriterion("certification =", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotEqualTo(String value) {
            addCriterion("certification <>", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationGreaterThan(String value) {
            addCriterion("certification >", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationGreaterThanOrEqualTo(String value) {
            addCriterion("certification >=", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationLessThan(String value) {
            addCriterion("certification <", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationLessThanOrEqualTo(String value) {
            addCriterion("certification <=", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationLike(String value) {
            addCriterion("certification like", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotLike(String value) {
            addCriterion("certification not like", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationIn(List<String> values) {
            addCriterion("certification in", values, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotIn(List<String> values) {
            addCriterion("certification not in", values, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationBetween(String value1, String value2) {
            addCriterion("certification between", value1, value2, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotBetween(String value1, String value2) {
            addCriterion("certification not between", value1, value2, "certification");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysIsNull() {
            addCriterion("continue_signed_days is null");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysIsNotNull() {
            addCriterion("continue_signed_days is not null");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysEqualTo(Integer value) {
            addCriterion("continue_signed_days =", value, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysNotEqualTo(Integer value) {
            addCriterion("continue_signed_days <>", value, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysGreaterThan(Integer value) {
            addCriterion("continue_signed_days >", value, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("continue_signed_days >=", value, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysLessThan(Integer value) {
            addCriterion("continue_signed_days <", value, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysLessThanOrEqualTo(Integer value) {
            addCriterion("continue_signed_days <=", value, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysIn(List<Integer> values) {
            addCriterion("continue_signed_days in", values, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysNotIn(List<Integer> values) {
            addCriterion("continue_signed_days not in", values, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysBetween(Integer value1, Integer value2) {
            addCriterion("continue_signed_days between", value1, value2, "continueSignedDays");
            return (Criteria) this;
        }

        public Criteria andContinueSignedDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("continue_signed_days not between", value1, value2, "continueSignedDays");
            return (Criteria) this;
        }



        public Criteria andAuthStatusIsNull() {
            addCriterion("auth_status is null");
            return (Criteria) this;
        }

        public Criteria andAuthStatusIsNotNull() {
            addCriterion("auth_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuthStatusEqualTo(Integer value) {
            addCriterion("auth_status =", value, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusNotEqualTo(Integer value) {
            addCriterion("auth_status <>", value, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusGreaterThan(Integer value) {
            addCriterion("auth_status >", value, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("auth_status >=", value, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusLessThan(Integer value) {
            addCriterion("auth_status <", value, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusLessThanOrEqualTo(Integer value) {
            addCriterion("auth_status <=", value, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusIn(List<Integer> values) {
            addCriterion("auth_status in", values, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusNotIn(List<Integer> values) {
            addCriterion("auth_status not in", values, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusBetween(Integer value1, Integer value2) {
            addCriterion("auth_status between", value1, value2, "authStatus");
            return (Criteria) this;
        }

        public Criteria andAuthStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("auth_status not between", value1, value2, "authStatus");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andAttributesIsNull() {
            addCriterion("attributes is null");
            return (Criteria) this;
        }

        public Criteria andAttributesIsNotNull() {
            addCriterion("attributes is not null");
            return (Criteria) this;
        }

        public Criteria andAttributesEqualTo(String value) {
            addCriterion("attributes =", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotEqualTo(String value) {
            addCriterion("attributes <>", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesGreaterThan(String value) {
            addCriterion("attributes >", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesGreaterThanOrEqualTo(String value) {
            addCriterion("attributes >=", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLessThan(String value) {
            addCriterion("attributes <", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLessThanOrEqualTo(String value) {
            addCriterion("attributes <=", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLike(String value) {
            addCriterion("attributes like", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotLike(String value) {
            addCriterion("attributes not like", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesIn(List<String> values) {
            addCriterion("attributes in", values, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotIn(List<String> values) {
            addCriterion("attributes not in", values, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesBetween(String value1, String value2) {
            addCriterion("attributes between", value1, value2, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotBetween(String value1, String value2) {
            addCriterion("attributes not between", value1, value2, "attributes");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearIsNull() {
            addCriterion("enrollment_year is null");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearIsNotNull() {
            addCriterion("enrollment_year is not null");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearEqualTo(Integer value) {
            addCriterion("enrollment_year =", value, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearNotEqualTo(Integer value) {
            addCriterion("enrollment_year <>", value, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearGreaterThan(Integer value) {
            addCriterion("enrollment_year >", value, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("enrollment_year >=", value, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearLessThan(Integer value) {
            addCriterion("enrollment_year <", value, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearLessThanOrEqualTo(Integer value) {
            addCriterion("enrollment_year <=", value, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearIn(List<Integer> values) {
            addCriterion("enrollment_year in", values, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearNotIn(List<Integer> values) {
            addCriterion("enrollment_year not in", values, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearBetween(Integer value1, Integer value2) {
            addCriterion("enrollment_year between", value1, value2, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andEnrollmentYearNotBetween(Integer value1, Integer value2) {
            addCriterion("enrollment_year not between", value1, value2, "enrollmentYear");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdIsNull() {
            addCriterion("stroll_school_id is null");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdIsNotNull() {
            addCriterion("stroll_school_id is not null");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdEqualTo(Integer value) {
            addCriterion("stroll_school_id =", value, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdNotEqualTo(Integer value) {
            addCriterion("stroll_school_id <>", value, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdGreaterThan(Integer value) {
            addCriterion("stroll_school_id >", value, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stroll_school_id >=", value, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdLessThan(Integer value) {
            addCriterion("stroll_school_id <", value, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdLessThanOrEqualTo(Integer value) {
            addCriterion("stroll_school_id <=", value, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdIn(List<Integer> values) {
            addCriterion("stroll_school_id in", values, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdNotIn(List<Integer> values) {
            addCriterion("stroll_school_id not in", values, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdBetween(Integer value1, Integer value2) {
            addCriterion("stroll_school_id between", value1, value2, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stroll_school_id not between", value1, value2, "strollSchoolId");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameIsNull() {
            addCriterion("stroll_school_name is null");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameIsNotNull() {
            addCriterion("stroll_school_name is not null");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameEqualTo(String value) {
            addCriterion("stroll_school_name =", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameNotEqualTo(String value) {
            addCriterion("stroll_school_name <>", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameGreaterThan(String value) {
            addCriterion("stroll_school_name >", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("stroll_school_name >=", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameLessThan(String value) {
            addCriterion("stroll_school_name <", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("stroll_school_name <=", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameLike(String value) {
            addCriterion("stroll_school_name like", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameNotLike(String value) {
            addCriterion("stroll_school_name not like", value, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameIn(List<String> values) {
            addCriterion("stroll_school_name in", values, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameNotIn(List<String> values) {
            addCriterion("stroll_school_name not in", values, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameBetween(String value1, String value2) {
            addCriterion("stroll_school_name between", value1, value2, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andStrollSchoolNameNotBetween(String value1, String value2) {
            addCriterion("stroll_school_name not between", value1, value2, "strollSchoolName");
            return (Criteria) this;
        }

        public Criteria andAdminIsNull() {
            addCriterion("admin is null");
            return (Criteria) this;
        }

        public Criteria andAdminIsNotNull() {
            addCriterion("admin is not null");
            return (Criteria) this;
        }

        public Criteria andAdminEqualTo(Boolean value) {
            addCriterion("admin =", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotEqualTo(Boolean value) {
            addCriterion("admin <>", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThan(Boolean value) {
            addCriterion("admin >", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThanOrEqualTo(Boolean value) {
            addCriterion("admin >=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThan(Boolean value) {
            addCriterion("admin <", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThanOrEqualTo(Boolean value) {
            addCriterion("admin <=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminIn(List<Boolean> values) {
            addCriterion("admin in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotIn(List<Boolean> values) {
            addCriterion("admin not in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminBetween(Boolean value1, Boolean value2) {
            addCriterion("admin between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotBetween(Boolean value1, Boolean value2) {
            addCriterion("admin not between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andAccountStatusIsNull() {
            addCriterion("account_status is null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusIsNotNull() {
            addCriterion("account_status is not null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusEqualTo(Integer value) {
            addCriterion("account_status =", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotEqualTo(Integer value) {
            addCriterion("account_status <>", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusGreaterThan(Integer value) {
            addCriterion("account_status >", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_status >=", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusLessThan(Integer value) {
            addCriterion("account_status <", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusLessThanOrEqualTo(Integer value) {
            addCriterion("account_status <=", value, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusIn(List<Integer> values) {
            addCriterion("account_status in", values, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotIn(List<Integer> values) {
            addCriterion("account_status not in", values, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusBetween(Integer value1, Integer value2) {
            addCriterion("account_status between", value1, value2, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("account_status not between", value1, value2, "accountStatus");
            return (Criteria) this;
        }

        public Criteria andBlueVIsNull() {
            addCriterion("blue_v is null");
            return (Criteria) this;
        }

        public Criteria andBlueVIsNotNull() {
            addCriterion("blue_v is not null");
            return (Criteria) this;
        }

        public Criteria andBlueVEqualTo(Boolean value) {
            addCriterion("blue_v =", value, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVNotEqualTo(Boolean value) {
            addCriterion("blue_v <>", value, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVGreaterThan(Boolean value) {
            addCriterion("blue_v >", value, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVGreaterThanOrEqualTo(Boolean value) {
            addCriterion("blue_v >=", value, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVLessThan(Boolean value) {
            addCriterion("blue_v <", value, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVLessThanOrEqualTo(Boolean value) {
            addCriterion("blue_v <=", value, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVIn(List<Boolean> values) {
            addCriterion("blue_v in", values, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVNotIn(List<Boolean> values) {
            addCriterion("blue_v not in", values, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVBetween(Boolean value1, Boolean value2) {
            addCriterion("blue_v between", value1, value2, "blueV");
            return (Criteria) this;
        }

        public Criteria andBlueVNotBetween(Boolean value1, Boolean value2) {
            addCriterion("blue_v not between", value1, value2, "blueV");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 20 20:47:20 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}