package com.fmx.xiaomeng.modules.admin.repository.model;

import java.util.Date;

public class AdminUserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.user_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.user_name
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.password
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.salt
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.email
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.mobile
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.status
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_user_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_time
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.school_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.user_id
     *
     * @return the value of admin_user.user_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.user_id
     *
     * @param userId the value for admin_user.user_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.user_name
     *
     * @return the value of admin_user.user_name
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.user_name
     *
     * @param userName the value for admin_user.user_name
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.password
     *
     * @return the value of admin_user.password
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.password
     *
     * @param password the value for admin_user.password
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.salt
     *
     * @return the value of admin_user.salt
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.salt
     *
     * @param salt the value for admin_user.salt
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.email
     *
     * @return the value of admin_user.email
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.email
     *
     * @param email the value for admin_user.email
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.mobile
     *
     * @return the value of admin_user.mobile
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.mobile
     *
     * @param mobile the value for admin_user.mobile
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.status
     *
     * @return the value of admin_user.status
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.status
     *
     * @param status the value for admin_user.status
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.create_user_id
     *
     * @return the value of admin_user.create_user_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.create_user_id
     *
     * @param createUserId the value for admin_user.create_user_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.create_time
     *
     * @return the value of admin_user.create_time
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.create_time
     *
     * @param createTime the value for admin_user.create_time
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.school_id
     *
     * @return the value of admin_user.school_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.school_id
     *
     * @param schoolId the value for admin_user.school_id
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}