package com.fmx.xiaomeng.modules.admin.repository.model;

public class AdminUserRoleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.user_id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.role_id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.id
     *
     * @return the value of admin_user_role.id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.id
     *
     * @param id the value for admin_user_role.id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.user_id
     *
     * @return the value of admin_user_role.user_id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.user_id
     *
     * @param userId the value for admin_user_role.user_id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.role_id
     *
     * @return the value of admin_user_role.role_id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.role_id
     *
     * @param roleId the value for admin_user_role.role_id
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}