package com.fmx.xiaomeng.modules.admin.repository.model;

import java.util.Date;

public class AdminCaptchaDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_captcha.uuid
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_captcha.code
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_captcha.expire_time
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_captcha.uuid
     *
     * @return the value of admin_captcha.uuid
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_captcha.uuid
     *
     * @param uuid the value for admin_captcha.uuid
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_captcha.code
     *
     * @return the value of admin_captcha.code
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_captcha.code
     *
     * @param code the value for admin_captcha.code
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_captcha.expire_time
     *
     * @return the value of admin_captcha.expire_time
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_captcha.expire_time
     *
     * @param expireTime the value for admin_captcha.expire_time
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}