package com.fmx.xiaomeng.modules.admin.repository.model;

public class AdminMenuDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.id
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.parent_id
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.name
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.url
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.perms
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private String perms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.type
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.icon
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_menu.order_num
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.id
     *
     * @return the value of admin_menu.id
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.id
     *
     * @param id the value for admin_menu.id
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.parent_id
     *
     * @return the value of admin_menu.parent_id
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.parent_id
     *
     * @param parentId the value for admin_menu.parent_id
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.name
     *
     * @return the value of admin_menu.name
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.name
     *
     * @param name the value for admin_menu.name
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.url
     *
     * @return the value of admin_menu.url
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.url
     *
     * @param url the value for admin_menu.url
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.perms
     *
     * @return the value of admin_menu.perms
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.perms
     *
     * @param perms the value for admin_menu.perms
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setPerms(String perms) {
        this.perms = perms == null ? null : perms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.type
     *
     * @return the value of admin_menu.type
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.type
     *
     * @param type the value for admin_menu.type
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.icon
     *
     * @return the value of admin_menu.icon
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.icon
     *
     * @param icon the value for admin_menu.icon
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_menu.order_num
     *
     * @return the value of admin_menu.order_num
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_menu.order_num
     *
     * @param orderNum the value for admin_menu.order_num
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}