package com.fmx.xiaomeng.modules.admin.repository.model;

public class AdminRoleMenuDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_menu.id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_menu.role_id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_menu.menu_id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    private Long menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_menu.id
     *
     * @return the value of admin_role_menu.id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_menu.id
     *
     * @param id the value for admin_role_menu.id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_menu.role_id
     *
     * @return the value of admin_role_menu.role_id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_menu.role_id
     *
     * @param roleId the value for admin_role_menu.role_id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_menu.menu_id
     *
     * @return the value of admin_role_menu.menu_id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_menu.menu_id
     *
     * @param menuId the value for admin_role_menu.menu_id
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }
}