package com.fmx.xiaomeng.modules.admin.repository.model;

import java.util.Date;

public class AdminRoleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.role_id
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.role_name
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.remark
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.create_user_id
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.create_time
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.role_id
     *
     * @return the value of admin_role.role_id
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.role_id
     *
     * @param roleId the value for admin_role.role_id
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.role_name
     *
     * @return the value of admin_role.role_name
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.role_name
     *
     * @param roleName the value for admin_role.role_name
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.remark
     *
     * @return the value of admin_role.remark
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.remark
     *
     * @param remark the value for admin_role.remark
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.create_user_id
     *
     * @return the value of admin_role.create_user_id
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.create_user_id
     *
     * @param createUserId the value for admin_role.create_user_id
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.create_time
     *
     * @return the value of admin_role.create_time
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.create_time
     *
     * @param createTime the value for admin_role.create_time
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}