package com.fmx.xiaomeng.modules.admin.repository.model;

public class BgConfigDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_bg_config.id
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_bg_config.school_id
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_bg_config.config_name
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_bg_config.config_value
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_bg_config.status
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_bg_config.remark
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_bg_config.id
     *
     * @return the value of admin_bg_config.id
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_bg_config.id
     *
     * @param id the value for admin_bg_config.id
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_bg_config.school_id
     *
     * @return the value of admin_bg_config.school_id
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_bg_config.school_id
     *
     * @param schoolId the value for admin_bg_config.school_id
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_bg_config.config_name
     *
     * @return the value of admin_bg_config.config_name
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_bg_config.config_name
     *
     * @param configName the value for admin_bg_config.config_name
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_bg_config.config_value
     *
     * @return the value of admin_bg_config.config_value
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_bg_config.config_value
     *
     * @param configValue the value for admin_bg_config.config_value
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_bg_config.status
     *
     * @return the value of admin_bg_config.status
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_bg_config.status
     *
     * @param status the value for admin_bg_config.status
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_bg_config.remark
     *
     * @return the value of admin_bg_config.remark
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_bg_config.remark
     *
     * @param remark the value for admin_bg_config.remark
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}