package com.fmx.xiaomeng.modules.admin.repository.model;

import java.util.Date;

public class CarouselDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.title
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.url
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.img
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.type
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.admin_user_id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private Long adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.school_id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lunbo_link.create_time
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.id
     *
     * @return the value of lunbo_link.id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.id
     *
     * @param id the value for lunbo_link.id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.title
     *
     * @return the value of lunbo_link.title
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.title
     *
     * @param title the value for lunbo_link.title
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.url
     *
     * @return the value of lunbo_link.url
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.url
     *
     * @param url the value for lunbo_link.url
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.img
     *
     * @return the value of lunbo_link.img
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.img
     *
     * @param img the value for lunbo_link.img
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.type
     *
     * @return the value of lunbo_link.type
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.type
     *
     * @param type the value for lunbo_link.type
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.admin_user_id
     *
     * @return the value of lunbo_link.admin_user_id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public Long getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.admin_user_id
     *
     * @param adminUserId the value for lunbo_link.admin_user_id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setAdminUserId(Long adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.school_id
     *
     * @return the value of lunbo_link.school_id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.school_id
     *
     * @param schoolId the value for lunbo_link.school_id
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lunbo_link.create_time
     *
     * @return the value of lunbo_link.create_time
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lunbo_link.create_time
     *
     * @param createTime the value for lunbo_link.create_time
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}