package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminCaptchaDO;

public interface AdminCaptchaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_captcha
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_captcha
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    int insert(AdminCaptchaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_captcha
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    int insertSelective(AdminCaptchaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_captcha
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    AdminCaptchaDO selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_captcha
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    int updateByPrimaryKeySelective(AdminCaptchaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_captcha
     *
     * @mbggenerated Thu Mar 30 22:51:34 CST 2023
     */
    int updateByPrimaryKey(AdminCaptchaDO record);
}