package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminRoleMenuDO;

public interface AdminRoleMenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    int insert(AdminRoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    int insertSelective(AdminRoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    AdminRoleMenuDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    int updateByPrimaryKeySelective(AdminRoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated Wed Mar 01 23:47:54 CST 2023
     */
    int updateByPrimaryKey(AdminRoleMenuDO record);
}