package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminUserTokenDO;

public interface AdminUserTokenDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated Thu Mar 02 01:14:06 CST 2023
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated Thu Mar 02 01:14:06 CST 2023
     */
    int insert(AdminUserTokenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated Thu Mar 02 01:14:06 CST 2023
     */
    int insertSelective(AdminUserTokenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated Thu Mar 02 01:14:06 CST 2023
     */
    AdminUserTokenDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated Thu Mar 02 01:14:06 CST 2023
     */
    int updateByPrimaryKeySelective(AdminUserTokenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated Thu Mar 02 01:14:06 CST 2023
     */
    int updateByPrimaryKey(AdminUserTokenDO record);

    AdminUserTokenDO queryByToken(String token);

    AdminUserTokenDO queryByUserId(long userId);
}