package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminMenuDO;
import com.fmx.xiaomeng.modules.systemsetting.service.param.BgMenuQueryParam;

import java.util.List;

public interface AdminMenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    int insert(AdminMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    int insertSelective(AdminMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    AdminMenuDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    int updateByPrimaryKeySelective(AdminMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated Wed Mar 01 23:48:13 CST 2023
     */
    int updateByPrimaryKey(AdminMenuDO record);

//    List<SysMenuEntity> selectAll();

    List<AdminMenuDO> queryByParam(BgMenuQueryParam bgMenuQueryParam);

    List<AdminMenuDO> list();
}