package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminUserDO;
import com.fmx.xiaomeng.modules.systemsetting.service.param.BgAdminUserPageQueryParam;

import java.util.List;

public interface AdminUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    int insert(AdminUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    int insertSelective(AdminUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    AdminUserDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    int updateByPrimaryKeySelective(AdminUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Tue Oct 17 23:19:33 CST 2023
     */
    int updateByPrimaryKey(AdminUserDO record);




    /**
     * 查询用户的所有权限
     * @param userId  用户ID
     */
    List<String> queryAllPerms(Long userId);

    /**
     * 查询用户的所有菜单ID
     */
    List<Long> queryAllMenuId(Long userId);

    /**
     * 根据用户名，查询系统用户（用户名就是账号，必须唯一）
     */
    AdminUserDO queryByUserName(String userName);



    List<AdminUserDO> pageQuery(BgAdminUserPageQueryParam pageQueryParam);

    long countByParam(BgAdminUserPageQueryParam param);
}
