package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminUserRoleDO;

import java.util.List;

public interface AdminUserRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    int insert(AdminUserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    int insertSelective(AdminUserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    AdminUserRoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    int updateByPrimaryKeySelective(AdminUserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated Wed Mar 01 23:46:40 CST 2023
     */
    int updateByPrimaryKey(AdminUserRoleDO record);

    void deleteByUserId(Long userId);

    List<Long> queryRoleByUserId(Long userId);

    int batchDeleteByRoleIdList(Long[] roleIds);
}