package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.AdminRoleDO;
import com.fmx.xiaomeng.modules.systemsetting.service.param.AdminRolePageQueryParam;

import java.util.List;

public interface AdminRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    int insert(AdminRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    int insertSelective(AdminRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    AdminRoleDO selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    int updateByPrimaryKeySelective(AdminRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Tue Aug 22 00:58:12 CST 2023
     */
    int updateByPrimaryKey(AdminRoleDO record);

    long countByParam(AdminRolePageQueryParam param);

    List<AdminRoleDO> pageQuery(AdminRolePageQueryParam param);

    void deleteByRoleIds(List<Long> roleIdList);

    List<Long> queryRoleIdList(Long createUserId);
}