package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.BgConfigDO;
import com.fmx.xiaomeng.modules.systemsetting.service.param.BgConfigPageQueryParam;
import com.fmx.xiaomeng.modules.systemsetting.service.param.BgConfigQueryParam;

import java.util.List;

public interface BgConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_bg_config
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_bg_config
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    int insert(BgConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_bg_config
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    int insertSelective(BgConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_bg_config
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    BgConfigDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_bg_config
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    int updateByPrimaryKeySelective(BgConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_bg_config
     *
     * @mbggenerated Sun Sep 08 16:03:35 CST 2024
     */
    int updateByPrimaryKey(BgConfigDO record);

    void update(BgConfigDO record);

    void removeByIds(List<Integer> idList);

    BgConfigDO queryByParam(BgConfigQueryParam param);

    List<BgConfigDO> pageQuery(BgConfigPageQueryParam param);

    Long countByParam(BgConfigPageQueryParam param);
}
