package com.fmx.xiaomeng.modules.admin.repository.dao;

import com.fmx.xiaomeng.modules.admin.repository.model.CarouselDO;

public interface CarouselDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo_link
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo_link
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    int insert(CarouselDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo_link
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    int insertSelective(CarouselDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo_link
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    CarouselDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo_link
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    int updateByPrimaryKeySelective(CarouselDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lunbo_link
     *
     * @mbggenerated Wed Mar 01 23:44:26 CST 2023
     */
    int updateByPrimaryKey(CarouselDO record);
}