package com.fmx.xiaomeng.modules.application.service.model;

import lombok.Data;

import java.util.Date;

/**
 * @Description
 * @Date 2025-12-20
 * @Author honghu
 **/
@Data
public class WxMsgSubscribeRecordModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.id
     *
     * @mbggenerated Sun Sep 08 14:17:25 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.user_id
     *
     * @mbggenerated Sun Sep 08 14:17:25 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.template_type
     *
     * @mbggenerated Sun Sep 08 14:17:25 CST 2024
     */
    private Integer templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.subscribe
     *
     * @mbggenerated Sun Sep 08 14:17:25 CST 2024
     */
    private Boolean subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.template_id
     *
     * @mbggenerated Sun Sep 08 14:17:25 CST 2024
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.left_times
     *
     * @mbggenerated Sun Sep 08 14:17:25 CST 2024
     */
    private Integer leftTimes;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_msg_subscribe_record.modified_time
     *
     * @mbggenerated Fri Dec 06 01:46:41 CST 2024
     */
    private Date modifiedTime;

    public Boolean getSubscribe() { return subscribe; }
    public Integer getLeftTimes() { return leftTimes; }
    public String getTemplateId() { return templateId; }
}
