package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.ArticleCategoryDO;

import java.util.List;

public interface ArticleCategoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    int insert(ArticleCategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    int insertSelective(ArticleCategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    ArticleCategoryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    int updateByPrimaryKeySelective(ArticleCategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbggenerated Sun Sep 03 01:24:20 CST 2023
     */
    int updateByPrimaryKey(ArticleCategoryDO record);

    List<ArticleCategoryDO> list();
}