package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.ArticleDO;
import com.fmx.xiaomeng.modules.application.service.param.ArticlePageQueryParam;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ArticleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    int insert(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    int insertSelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    ArticleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    int updateByPrimaryKeySelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Sat Nov 23 02:04:07 CST 2024
     */
    int updateByPrimaryKey(ArticleDO record);




    long countByParam(ArticlePageQueryParam articlePageQueryParam);

    List<ArticleDO> pageQuery(ArticlePageQueryParam articlePageQueryParam);

    List<ArticleDO> topArticle(@Param("schoolId") Integer schoolId);

    List<ArticleDO> topTenDay(Integer schoolId);

    List<ArticleDO> topTenWeek(Integer schoolId);

    List<ArticleDO> topTenMonth(Integer schoolId);

    void setTop(Long articleId);

    void cancelTop(Long articleId);


    void plusThumbUpCount(Long articleId);

    void minusThumbUpCount(Long articleId);

    void plusViewCount(@Param("articleId") Long articleId, @Param("count") Integer count, @Param("randomCount") Integer randomCount);

    void plusCollectCount(Long articleId);

    void minusCollectCount(Long articleId);

    void plusCommentCount(Long articleId);

    void delete(Long articleId);


    /**
     * 更新我的帖子中个人信息
     * @param userId
     * @param avatar
     * @param userNickName
     */
    void updateMyArticleNoAnonymous(Long userId, String avatar, String userNickName);

    List<ArticleDO> queryWxGroupArticleInfo(Integer schoolId, Date startTime);

    Long countYesterdayArticleNum(@Param("schoolId") Integer schoolId);

    Long countTodayArticleNum(@Param("schoolId") Integer schoolId);
}
