package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.ArticleCommentDO;
import com.fmx.xiaomeng.modules.application.service.param.CommentPageQueryParam;
import com.fmx.xiaomeng.modules.application.service.param.CommentParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleCommentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    int insert(ArticleCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    int insertSelective(ArticleCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    ArticleCommentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    int updateByPrimaryKeySelective(ArticleCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Fri Mar 28 20:44:31 CST 2025
     */
    int updateByPrimaryKey(ArticleCommentDO record);





    Long count(CommentPageQueryParam articlePageQueryParam);

    List<ArticleCommentDO> pageQuery(@Param("param") CommentPageQueryParam commentPageQueryParam);

    void plusThumbUpCount(Long commentId);


    void minusThumbUpCount(Long commentId);

    int deleteByParam(CommentParam param);

    List<ArticleCommentDO> queryByParam(CommentParam param);

    /**
     * 更新我的评论
     * @param userId
     * @param avatar
     * @param userNickName
     */
    void updateMyCommentsNoAnonymous(Long userId, String avatar, String userNickName);

    /**
     * 更新回复我的评论
     * @param userId
     * @param userNickName
     */
    void updateReplyMeComments(Long userId, String userNickName, String anonymousName);

}
