package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.CollectDO;
import com.fmx.xiaomeng.modules.application.service.param.CollectPageQueryParam;
import com.fmx.xiaomeng.modules.application.service.param.CollectParam;

import java.util.List;

public interface CollectDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    int insert(CollectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    int insertSelective(CollectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    CollectDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    int updateByPrimaryKeySelective(CollectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated Tue Mar 05 01:39:06 CST 2024
     */
    int updateByPrimaryKey(CollectDO record);



    List<CollectDO> select(CollectParam param);

    void delete(CollectParam param);

    Long count(Long userId);

    long countByParam(CollectPageQueryParam pageQueryParam);

    List<CollectDO> pageQuery(CollectPageQueryParam pageQueryParam);

}