package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.DingDO;
import com.fmx.xiaomeng.modules.application.service.param.DingParam;

import java.util.List;

public interface DingDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_zhu
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    int insert(DingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ding_zhu
     *
     * @mbggenerated Sun Apr 02 14:52:53 CST 2023
     */
    int insertSelective(DingDO record);

    List<DingDO> queryByParam(DingParam dingParam);

    void delete(DingParam dingParam);
}