package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.MediaCheckRecordDO;

public interface MediaCheckRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_check_record
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_check_record
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    int insert(MediaCheckRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_check_record
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    int insertSelective(MediaCheckRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_check_record
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    MediaCheckRecordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_check_record
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    int updateByPrimaryKeySelective(MediaCheckRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_check_record
     *
     * @mbggenerated Sun Oct 15 15:35:03 CST 2023
     */
    int updateByPrimaryKey(MediaCheckRecordDO record);

    MediaCheckRecordDO selectByTraceId(String traceId);
}