package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.MockArticleDO;
import com.fmx.xiaomeng.modules.application.service.param.ArticlePageQueryParam;

import java.util.List;

public interface MockArticleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_article
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_article
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    int insert(MockArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_article
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    int insertSelective(MockArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_article
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    MockArticleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_article
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    int updateByPrimaryKeySelective(MockArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_article
     *
     * @mbggenerated Thu Apr 03 20:40:57 CST 2025
     */
    int updateByPrimaryKey(MockArticleDO record);


    MockArticleDO queryOneBySchool(Integer schoolId);

    long countByParam(ArticlePageQueryParam param);

    List<MockArticleDO> pageQuery(ArticlePageQueryParam param);

    void deleteById(Long articleId);
}
