package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.NotificationDO;
import com.fmx.xiaomeng.modules.application.service.param.NotificationPageQueryParam;
import com.fmx.xiaomeng.modules.application.service.param.NotificationParam;

import java.util.List;

public interface NotificationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    int insert(NotificationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    int insertSelective(NotificationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    NotificationDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    int updateByPrimaryKeySelective(NotificationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Fri Dec 20 02:42:14 CST 2024
     */
    int updateByPrimaryKey(NotificationDO record);




    long count(NotificationPageQueryParam param);

    List<NotificationDO> pageQuery(NotificationPageQueryParam articlePageQueryParam);

    List<NotificationDO> queryByParam(NotificationParam param);

    void setAlreadyRead(Long targetUserId, List<Integer> noticeTypeList);

    void deleteByParam(NotificationParam param);

    int countUnreadMsgCount(Long targetUserId, List<Integer> noticeTypeList);

    void updateAlreadyReadViolationNotification(Long targetUserId);

    NotificationDO getNewestSystemNotice(NotificationParam param);

    void deleteById(Long id);
}
