package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.OnlineTimeStatisticDO;

public interface OnlineTimeStatisticDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_time_statistic
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    int insert(OnlineTimeStatisticDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_time_statistic
     *
     * @mbggenerated Mon Jan 22 22:07:18 CST 2024
     */
    int insertSelective(OnlineTimeStatisticDO record);

    OnlineTimeStatisticDO select(Long userId, String dateKey);
}