package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.admin.service.param.ReportPageQueryParam;
import com.fmx.xiaomeng.modules.application.repository.model.ReportRecordDO;
import com.fmx.xiaomeng.modules.application.service.param.ReportQueryParam;

import java.util.List;

public interface ReportRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_record
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_record
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    int insert(ReportRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_record
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    int insertSelective(ReportRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_record
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    ReportRecordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_record
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    int updateByPrimaryKeySelective(ReportRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_record
     *
     * @mbggenerated Sun Jun 16 00:26:58 CST 2024
     */
    int updateByPrimaryKey(ReportRecordDO record);

    long countByParam(ReportPageQueryParam param);

    List<ReportRecordDO> pageQuery(ReportPageQueryParam param);

    ReportRecordDO queryByParam(ReportQueryParam param);

}
