package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.SysLogDO;

public interface SysLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sun Sep 01 03:31:28 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sun Sep 01 03:31:28 CST 2024
     */
    int insert(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sun Sep 01 03:31:28 CST 2024
     */
    int insertSelective(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sun Sep 01 03:31:28 CST 2024
     */
    SysLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sun Sep 01 03:31:28 CST 2024
     */
    int updateByPrimaryKeySelective(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Sun Sep 01 03:31:28 CST 2024
     */
    int updateByPrimaryKey(SysLogDO record);
}