package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.ThumbUpDO;
import com.fmx.xiaomeng.modules.application.service.param.ThumbUpParam;

import java.util.List;

public interface ThumbUpDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    int insert(ThumbUpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    int insertSelective(ThumbUpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    ThumbUpDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    int updateByPrimaryKeySelective(ThumbUpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbggenerated Mon Dec 23 02:09:16 CST 2024
     */
    int updateByPrimaryKey(ThumbUpDO record);


    ThumbUpDO queryByParam(ThumbUpParam param);

    @Deprecated
    List<ThumbUpDO> pageQuery(ThumbUpParam param);

    int countByParam(ThumbUpParam param);

    void deleteByParam(ThumbUpParam thumbUpParam);

    int delete(com.fmx.xiaomeng.modules.application.repository.model.ThumbUpDO record);
}
