package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.application.repository.model.UserBlackDO;

public interface UserBlackDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    int insert(UserBlackDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    int insertSelective(UserBlackDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    UserBlackDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    int updateByPrimaryKeySelective(UserBlackDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_black
     *
     * @mbggenerated Sun Apr 13 13:59:47 CST 2025
     */
    int updateByPrimaryKey(UserBlackDO record);

    UserBlackDO queryByUserIdAndBlackedUserId(Long userId, Long blackedUserId);

}
