package com.fmx.xiaomeng.modules.application.repository.dao;

import com.fmx.xiaomeng.modules.admin.request.UserPageQueryParam;
import com.fmx.xiaomeng.modules.application.repository.model.UserDO;
import com.fmx.xiaomeng.modules.application.repository.model.UserDOExample;

import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    List<UserDO> selectByExample(UserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Sep 20 20:47:20 CST 2025
     */
    int updateByPrimaryKey(UserDO record);




    int updateByUserId(UserDO record);


    UserDO selectByUserId(Long userId);

    UserDO selectByOpenId(String openId);
    UserDO selectByUnionId(String unionId);

    long count(UserPageQueryParam params);

    List<UserDO> pageQuery(UserPageQueryParam params);

    long countByExample(UserDOExample example);

    void addScore(Long userId, Integer score);

    void updateSignInContinuesDays(Long userId, Integer continueSignedDays);


    void addViolationTimes(Long userId);

    List<UserDO> listMockUser();

    void initAnonymousAvatar(Long userId, String anonymousAvatar);
    /**
     * 设置用户蓝V状态
     */
    void setBlueV(Long userId, Boolean blueV);
}
